    Author: Mikael Koli
    email: koli.mikael@gmail.com
    Date: 19.01.2019
    State: Stable

# Demonstration of Finnish Business Portal

This file demonstrates the use of Finnish Business Portal Python API. In order to replicate the demo, please make sure you have appropriate version of Python 3 and the libraries Pandas and Requests and their dependencies. After this, download this application from the source.

## Navigation:
* [Setup](#H0)
  * [Import the module](#H0_imports)
* [Parameters](#H1)
* [Example Searches](#H20)
* [Example Application](#H3)

## Setup<a class="anchor" id="H0"></a>

In [2]:
import datetime
import platform
import os
import sys

print(f'Python version: {platform.python_version()}')
print(f'''
Time of Run: 
    Year:    {datetime.datetime.now().year}
    Month:   {datetime.datetime.now().month}
    Day:     {datetime.datetime.now().day}
''')

Python version: 3.10.6

Time of Run:
    Year:    2023
    Month:   2
    Day:     6

### Import the module<a class="anchor" id="H0_imports"></a>

In [3]:
import finnish_business_portal as busportal

## Parameters<a class="anchor" id="H1"></a>

The API options can be found using "api_infos" or "api_options" attributes of the class. You can copy-paste the string as an initial argument for the class initiation. This is the only required argument.

In [2]:
busportal.SearchModel.api_infos

{'BisCompanyDetails': 'Nouda yritys- ja yhteisötietojärjestelmään merkitty yritys Y-tunnuksen avulla',
 'BisCompany': 'Hae yritys- ja yhteisötietojärjestelmään merkittyjä yrityksiä hakutermien avulla',
 'TradeRegisterCompanyDetails': 'Nouda kaupparekisteriin merkitty yritys Y-tunnuksen avulla',
 'TradeRegisterCompany': 'Hae kaupparekisteriin merkittyjä yrityksiä hakutermien avulla',
 'TrCompanyPublicNotice': 'Hae kaupparekisterin kuulutustietoja hakutermien avulla'}

In [3]:
busportal.SearchModel.api_options

['BisCompanyDetails',
 'BisCompany',
 'TradeRegisterCompanyDetails',
 'TradeRegisterCompany',
 'TrCompanyPublicNotice']

In [4]:
portal = busportal.SearchModel("BisCompany")

You can get allowed parameters for your selected API using method ".parameter_options". For more detailed information, use ".parameter_infos".

In [5]:
portal.parameter_options

['totalResults',
 'maxResults',
 'resultsFrom',
 'name',
 'businessId',
 'registeredOffice',
 'streetAddressPostCode',
 'companyForm',
 'businessLine',
 'businessLineCode',
 'companyRegistrationFrom',
 'companyRegistrationTo']

In [18]:
portal.parameter_infos

{'totalResults': {'name': 'totalResults',
  'description': 'Jos arvoksi valitaan true, hakutuloksen kokonaismäärä sisältyy tuloksiin totalResults-arvona. Muussa tapauksessa totalResults-arvo asetetaan arvoksi -1',
  'defaultValue': 'false',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'enum': ['true', 'false']},
 'maxResults': {'name': 'maxResults',
  'description': 'Tulosten enimmäismääränä on annettu luku',
  'defaultValue': '10',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'minimum': '0.0',
  'maximum': '1000.0'},
 'resultsFrom': {'name': 'resultsFrom',
  'description': 'Tuloksena annetaan ne tulokset, jotka alkavat annetulla numerolla',
  'defaultValue': '0',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'minimum': '0.0',
  'maximum': '1000.0'},
 'name': {'name': 'name',
  'description': ' Yrityksen nimi tai sen alkuosa',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'businessId': {'name': 'businessId',
  'description': 'Y-tunnus',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'registeredOffice': {'name': 'registeredOffice',
  'description': ' Yrityksen kotipaikka suomeksi tai ruotsiksi. Oltava tarkka vastine.',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'streetAddressPostCode': {'name': 'streetAddressPostCode',
  'description': "Company's registered visiting address postcode",
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'companyForm': {'name': 'companyForm',
  'description': 'Yritysmuoto',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'enum': ['AOY', 'OYJ', 'OY', 'OK', 'VOJ']},
 'businessLine': {'name': 'businessLine',
  'description': 'Toimiala tai sen alkuosa millä tahansa kielellä.',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'businessLineCode': {'name': 'businessLineCode',
  'description': '<a href="http://www.stat.fi/meta/luokitukset/toimiala/001-2008/index.html"> Toimialakoodi</a> tai sen alkuosa',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'companyRegistrationFrom': {'name': 'companyRegistrationFrom',
  'description': ' Yrityksen Y-tunnuksen rekisteröintiajankohta alkaen (ISO 8601 Helsinki muodossa)',
  'defaultValue': '2014-02-28',
  'required': False,
  'type': 'string',
  'paramType': 'query'},
 'companyRegistrationTo': {'name': 'companyRegistrationTo',
  'description': ' Yrityksen rekisteröintiajankohta päättyen (ISO 8601 Helsinki muodossa)',
  'required': False,
  'type': 'string',
  'paramType': 'query'}}

In [6]:
# Returning only two parameters for clarity
{key: val for i, (key, val) in enumerate(portal.parameter_infos.items()) if i < 2}

{'totalResults': {'name': 'totalResults',
  'description': 'Jos arvoksi valitaan true, hakutuloksen kokonaismäärä sisältyy tuloksiin totalResults-arvona. Muussa tapauksessa totalResults-arvo asetetaan arvoksi -1',
  'defaultValue': 'false',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'enum': ['true', 'false']},
 'maxResults': {'name': 'maxResults',
  'description': 'Tulosten enimmäismääränä on annettu luku',
  'defaultValue': '10',
  'required': False,
  'type': 'string',
  'paramType': 'query',
  'minimum': '0.0',
  'maximum': '1000.0'}}

There is also a method ".help()" to give thorough information of the APIs.

There are also other keyword arguments you can use in the class initiation.

These are:
- wait_time: seconds to wait before each call to slow down querying. Be nice to the APIs. (default: 2)
- loop_results: True to loop all found entries (causing multiple additional queries), False to return the first query (default: False) 
- deep: True to go through all detailed URLs giving more data but more queries (default: False)

## Example Searches<a class="anchor" id="H20"></a>

In [21]:
portal = busportal.SearchModel("BisCompany")
portal.search(companyRegistrationFrom='2022-02-20', companyRegistrationTo='2022-02-21')

INFO:finnish_business_portal.core.model:1 queries to make (time taken > 2)...
WARNING:finnish_business_portal.core.model:Not all entries in the API searched (10), set loop_results=True to get all.

{"type":"fi.prh.opendata.bis","version":"1","totalResults":-1,"resultsFrom":0,"previousResultsUri":null,"nextResultsUri":"http://avoindata.prh.fi/opendata/bis/v1?totalResults=false&maxResults=10&resultsFrom=10&companyRegistrationFrom=2022-02-20&companyRegistrationTo=2022-02-21","exceptionNoticeUri":null,"results":[{"businessId":"3269978-4","name":"RIKOVA Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269978-4"},{"businessId":"3269855-4","name":"TL-Tiimi Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269855-4"},{"businessId":"3269922-3","name":"Beresta Trade Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269922-3"},{"businessId":"3269909-8","name":"SKY CUBE OY","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269909-8"},{"businessId":"3269858-9","name":"Ratkon Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269858-9"},{"businessId":"3269794-9","name":"S.Aspholm&Company Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269794-9"},{"businessId":"3270383-5","name":"Fusion Technologies Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3270383-5"},{"businessId":"3269864-2","name":"K Isosomppi Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269864-2"},{"businessId":"3269934-6","name":"J2L Invest Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269934-6"},{"businessId":"3269890-9","name":"Deja-vu 2022 Oy","registrationDate":"2022-02-21","companyForm":"OY","detailsUri":"http://avoindata.prh.fi/opendata/bis/v1/3269890-9"}]}

In [7]:
portal = busportal.SearchModel("BisCompany")
portal.search(name=["Fortum", "Nokia"], companyForm="oy")

INFO:finnish_business_portal.core.model:2 queries to make (time taken > 4)...
WARNING:finnish_business_portal.core.model:Not all entries in the API searched (10), set loop_results=True to get all.

The search returned itself and no any data. The data is in the attribute "results" but by default this is just a list of dictionaries. To turn the data to table format, use to_frame() (requires Pandas) and then access the results attribute.

In [22]:
portal.to_frame().results

,name,registrationDate,companyForm,detailsUri
businessId,,,,
3269978-4,RIKOVA Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269978-4
3269855-4,TL-Tiimi Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269855-4
3269922-3,Beresta Trade Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269922-3
3269909-8,SKY CUBE OY,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269909-8
3269858-9,Ratkon Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269858-9
3269794-9,S.Aspholm&Company Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269794-9
3270383-5,Fusion Technologies Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3270383-5
3269864-2,K Isosomppi Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269864-2
3269934-6,J2L Invest Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269934-6
3269890-9,Deja-vu 2022 Oy,2022-02-21,OY,http://avoindata.prh.fi/opendata/bis/v1/3269890-9

The class does not loop the results by default and is showing only the number of companies specified in max_results. To get all of the companies, 
a) increase "max_results" (may crash the query if too large) or 
b) set "loop_results_" to True

In [9]:
portal = busportal.SearchModel("BisCompany", loop_results=True)
portal.search(name=["Fortum", "Nokia"], companyForm="oy")
portal.to_frame().results

INFO:finnish_business_portal.core.model:2 queries to make (time taken > 4)...

,name,registrationDate,companyForm,detailsUri
businessId,,,,
3270870-8,Fortum Bio Oy,2022-02-24,OY,http://avoindata.prh.fi/opendata/bis/v1/3270870-8
3270880-4,Fortum Kasvu Oy,2022-02-24,OY,http://avoindata.prh.fi/opendata/bis/v1/3270880-4
3258835-5,Fortum TwoGether Oy,2022-01-03,OY,http://avoindata.prh.fi/opendata/bis/v1/3258835-5
3231783-8,Fortum Alku Oy,2021-08-25,OY,http://avoindata.prh.fi/opendata/bis/v1/3231783-8
3194389-6,Fortum RES Oy,2021-02-25,OY,http://avoindata.prh.fi/opendata/bis/v1/3194389-6
3114423-4,Fortum Clean Oy,2020-01-24,OY,http://avoindata.prh.fi/opendata/bis/v1/3114423-4
2679784-7,Fortum Real Estate Oy,2015-03-03,OY,http://avoindata.prh.fi/opendata/bis/v1/2679784-7
3332493-3,Nokian Autopajat Oy,2022-12-20,OY,http://avoindata.prh.fi/opendata/bis/v1/3332493-3
3325649-1,Nokian kirpputori ja outlet oy,2022-11-16,OY,http://avoindata.prh.fi/opendata/bis/v1/3325649-1
3285587-1,Nokian Kivi Oy,2022-05-06,OY,http://avoindata.prh.fi/opendata/bis/v1/3285587-1
3251237-7,Nokian PuuSepät oy,2021-11-28,OY,http://avoindata.prh.fi/opendata/bis/v1/3251237-7
3247425-1,Kauniskaluste Oy,2021-11-10,OY,http://avoindata.prh.fi/opendata/bis/v1/3247425-1
3210190-6,Nokiakka Oy,2021-05-10,OY,http://avoindata.prh.fi/opendata/bis/v1/3210190-6
3196409-9,Nokian Jamastar Oy,2021-03-09,OY,http://avoindata.prh.fi/opendata/bis/v1/3196409-9
3144949-2,Nokian Sukellustyö Oy,2020-07-02,OY,http://avoindata.prh.fi/opendata/bis/v1/3144949-2
3130963-3,Nokian Pizzamestarit Oy,2020-04-14,OY,http://avoindata.prh.fi/opendata/bis/v1/3130963-3
3121339-1,Inkoon Venehotelli Oy,2020-02-24,OY,http://avoindata.prh.fi/opendata/bis/v1/3121339-1
3120612-4,Noot Oy,2020-02-20,OY,http://avoindata.prh.fi/opendata/bis/v1/3120612-4
3117113-6,Retip Oy,2020-02-05,OY,http://avoindata.prh.fi/opendata/bis/v1/3117113-6
3114976-4,Nokian Vuokravarastot Oy,2020-01-28,OY,http://avoindata.prh.fi/opendata/bis/v1/3114976-4
3010033-6,Tevoks Oy,2019-07-02,OY,http://avoindata.prh.fi/opendata/bis/v1/3010033-6
2947233-5,Nokian Saneeraus Asiantuntijat Oy,2018-10-19,OY,http://avoindata.prh.fi/opendata/bis/v1/2947233-5
2892396-6,Nokian JV-Saneeraus Oy,2018-02-09,OY,http://avoindata.prh.fi/opendata/bis/v1/2892396-6
2889182-9,Nokian Timanttityö Oy,2018-02-01,OY,http://avoindata.prh.fi/opendata/bis/v1/2889182-9
2733848-2,Nokian Jäähalli Oy,2015-12-29,OY,http://avoindata.prh.fi/opendata/bis/v1/2733848-2
2726719-4,Nokian Neulomo Oy,2015-11-25,OY,http://avoindata.prh.fi/opendata/bis/v1/2726719-4
2655044-9,Nokia Technologies Oy,2014-11-19,OY,http://avoindata.prh.fi/opendata/bis/v1/2655044-9
2644660-9,Nokian Ramirakennus Oy,2014-09-30,OY,http://avoindata.prh.fi/opendata/bis/v1/2644660-9
2636612-3,Kirstua Vesa Oy,2014-08-22,OY,http://avoindata.prh.fi/opendata/bis/v1/2636612-3

In [10]:
portal = busportal.SearchModel("BisCompany", loop_results=False, deep=True)
portal.search(name=["Fortum", "Nokia"], companyForm="oy", total_results="True")
portal.to_frame().results

INFO:finnish_business_portal.core.model:2 queries to make (time taken > 4)...
WARNING:finnish_business_portal.core.model:Not all entries in the API searched (10 vs 22), set loop_results=True to get all.
INFO:finnish_business_portal.core.model:17 queries to make (time taken > 34)...

,name,registrationDate,companyForm,detailsUri,liquidations,names,auxiliaryNames,addresses,companyForms,businessLines,languages,registedOffices,contactDetails,registeredEntries,businessIdChanges
businessId,,,,,,,,,,,,,,,
3270870-8,Fortum Bio Oy,2022-02-24,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Bi...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3270880-4,Fortum Kasvu Oy,2022-02-24,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Ka...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3258835-5,Fortum TwoGether Oy,2022-01-03,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Tw...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3231783-8,Fortum Alku Oy,2021-08-25,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Al...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3194389-6,Fortum RES Oy,2021-02-25,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum RE...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3114423-4,Fortum Clean Oy,2020-01-24,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Cl...",[],"[{'careOf': None, 'street': 'Keilalahdentie 2-...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '70220', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
2679784-7,Fortum Real Estate Oy,2015-03-03,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Fortum Re...",[],"[{'careOf': None, 'street': 'PL 100', 'postCod...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '68209', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'ESPOO', '...","[{'version': 1, 'value': '010 4511', 'type': '...","[{'authority': 1, 'register': 4, 'status': 1, ...","[{'changeDate': '2015-06-30', 'change': 'DIF',..."
3332493-3,Nokian Autopajat Oy,2022-12-20,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Au...",[],"[{'careOf': None, 'street': 'Katsastajankatu 1...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '45201', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3325649-1,Nokian kirpputori ja outlet oy,2022-11-16,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian ki...",[],"[{'careOf': None, 'street': 'Kissankulmantie 6...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '47199', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...","[{'version': 1, 'value': '0400737974', 'type':...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3285587-1,Nokian Kivi Oy,2022-05-06,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Ki...",[],"[{'careOf': None, 'street': 'Kirkonkulma 1', '...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '23700', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...","[{'version': 1, 'value': '0408349424', 'type':...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3251237-7,Nokian PuuSepät oy,2021-11-28,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Pu...",[],"[{'careOf': None, 'street': 'Vesunninraitti 84...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '31020', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3247425-1,Kauniskaluste Oy,2021-11-10,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Kauniskal...","[{'order': 2, 'version': 1, 'name': 'Nokian Di...","[{'careOf': None, 'street': 'Rautatienkatu 6',...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '47199', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...",[],"[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3210190-6,Nokiakka Oy,2021-05-10,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokiakka ...","[{'order': 2, 'version': 1, 'name': 'Noki Cate...","[{'careOf': None, 'street': 'Kalastajankatu 20...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '10390', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'JOENSUU',...","[{'version': 1, 'value': 'www.nokiakka.fi', 't...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3196409-9,Nokian Jamastar Oy,2021-03-09,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Ja...",[],"[{'careOf': 'Martti Hakkarainen', 'street': 'J...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '68100', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'TAMPERE',...","[{'version': 1, 'value': '+358400859995', 'typ...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3144949-2,Nokian Sukellustyö Oy,2020-07-02,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Su...","[{'order': 2, 'version': 1, 'name': 'Nokia Div...","[{'careOf': None, 'street': 'Muonamiehentie 2'...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '74909', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...","[{'version': 1, 'value': '+358405371189', 'typ...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3130963-3,Nokian Pizzamestarit Oy,2020-04-14,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Nokian Pi...",[],"[{'careOf': None, 'street': 'Välikatu 14', 'po...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '56101', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'NOKIA', '...","[{'version': 1, 'value': 'www.pizzamestarit.fi...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]
3121339-1,Inkoon Venehotelli Oy,2020-02-24,OY,None,[],"[{'order': 0, 'version': 1, 'name': 'Inkoon Ve...","[{'order': 2, 'version': 1, 'name': 'Espoon Ve...","[{'careOf': None, 'street': 'Kalasatamantie 13...","[{'version': 1, 'name': 'Osakeyhtiö', 'type': ...","[{'order': 0, 'version': 1, 'code': '52100', '...","[{'version': 1, 'name': 'Finnish', 'registrati...","[{'order': 0, 'version': 1, 'name': 'INKOO', '...","[{'version': 1, 'value': '09 31577549', 'type'...","[{'authority': 1, 'register': 4, 'status': 1, ...",[]

And finally testing with other API.

In [5]:
portal.api = "TradeRegisterCompany"
portal.parameter_options

['totalResults',
 'maxResults',
 'resultsFrom',
 'name',
 'businessId',
 'registeredOffice',
 'companyForm',
 'companyRegistrationFrom',
 'companyRegistrationTo',
 'companyChangedSince',
 'recordNumber',
 'entryCode',
 'noticeRegistrationFrom',
 'noticeRegistrationTo',
 'noticeRegistrationType']

In [6]:
portal.search(name="Renk", company_registration_from="2000-01-01")
portal.to_frame().results

INFO:finnish_business_portal.core.model:1 queries to make (time taken > 2)...
WARNING:finnish_business_portal.core.connection:Failed to connect to http://avoindata.prh.fi/tr/v1?totalResults=false&maxResults=10&resultsFrom=0&name=Renk&companyRegistrationFrom=2000-01-01

Too Many Requests

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Some of the columns may seem to be confusing as they are list of dictionaries. You can "flat" them passing True to the to_frame method.

In [ ]:
portal.to_frame(True).results

But on the other hands, they were list of dicts for a reason.

## Example Application<a class="anchor" id="H3"></a>

In [7]:
import pandas as pd

Using a bit of data manipulation with Pandas, one can put the data any desirable format.

In [17]:
portal = busportal.SearchModel("BisCompany", loop_results=False, deep=True)
#portal.search(name="Fortum", companyForm="oy", companyRegistrationFrom="2000-01-01")
portal.search(companyForm="oy", registrationDate="2000-01-01")

KeyError: 'Parameter registrationDate not found.'

In [15]:
df_fortum = portal.to_frame(True).results

KeyError: "None of ['businessId'] are in the columns"

If case you need to get street addresses from a company/companies, you can do it like the following:

In [10]:
first_level = "address"
second_level = ("street", "postCode", "city", "country", "endDate")
(
    df_fortum[
        [col for col in df_fortum.columns 
         if col[0].startswith(first_level) 
         and col[1] in second_level]
    ]
    .stack(0)
).join(df_fortum["name"])

                          city country     endDate postCode  \
businessId
3270870-8  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
3270880-4  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
3258835-5  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
3231783-8  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
3194389-6  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
3114423-4  addresses 0   ESPOO    None        None    02150
           addresses 1  FORTUM    None        None    00048
2679784-7  addresses 0  FORTUM    None        None    00048
           addresses 1  FORTUM    None  2017-12-18    00048
           addresses 2   ESPOO     NaN         NaN    02150
2481332-1  addresses 0  FORTUM    None  2017-12-18    00048
           addresses 1   ESPOO    None  2017-12-18    02150
           addresses 2   ESPOO     NaN         NaN    02150
           addresses 3  FORTUM     NaN         NaN    00048
2481336-4  addresses 0  FORTUM    None  2017-12-18    00048
           addresses 1   ESPOO    None  2017-12-18    02150
           addresses 2   ESPOO     NaN         NaN    02150
           addresses 3  FORTUM     NaN         NaN    00048
2185030-3  addresses 0  FORTUM    None  2017-12-18    00048
           addresses 1   ESPOO    None  2017-12-18    02150
           addresses 2   ESPOO     NaN         NaN    02150
           addresses 3  FORTUM     NaN         NaN    00048

                                    street                              name
businessId
3270870-8  addresses 0  Keilalahdentie 2-4                     Fortum Bio Oy
           addresses 1              PL 100                     Fortum Bio Oy
3270880-4  addresses 0  Keilalahdentie 2-4                   Fortum Kasvu Oy
           addresses 1              PL 100                   Fortum Kasvu Oy
3258835-5  addresses 0  Keilalahdentie 2-4               Fortum TwoGether Oy
           addresses 1              PL 100               Fortum TwoGether Oy
3231783-8  addresses 0  Keilalahdentie 2-4                    Fortum Alku Oy
           addresses 1              PL 100                    Fortum Alku Oy
3194389-6  addresses 0  Keilalahdentie 2-4                     Fortum RES Oy
           addresses 1              PL 100                     Fortum RES Oy
3114423-4  addresses 0  Keilalahdentie 2-4                   Fortum Clean Oy
           addresses 1              PL 100                   Fortum Clean Oy
2679784-7  addresses 0              PL 100             Fortum Real Estate Oy
           addresses 1    Keilaniementie 1             Fortum Real Estate Oy
           addresses 2  Keilalahdentie 2-4             Fortum Real Estate Oy
2481332-1  addresses 0    Keilaniementie 1  Fortum Power and Heat Holding Oy
           addresses 1    Keilaniementie 1  Fortum Power and Heat Holding Oy
           addresses 2  Keilalahdentie 2-4  Fortum Power and Heat Holding Oy
           addresses 3              PL 100  Fortum Power and Heat Holding Oy
2481336-4  addresses 0    Keilaniementie 1                    Fortum Norm Oy
           addresses 1    Keilaniementie 1                    Fortum Norm Oy
           addresses 2  Keilalahdentie 2-4                    Fortum Norm Oy
           addresses 3              PL 100                    Fortum Norm Oy
2185030-3  addresses 0                PL 1              Fortum Renewables Oy
           addresses 1    Keilaniementie 1              Fortum Renewables Oy
           addresses 2  Keilalahdentie 2-4              Fortum Renewables Oy
           addresses 3              PL 100              Fortum Renewables Oy

What happens here is that we take only the columns that have word "address" in the first level (ie. addresses 0) and the second level must in the list "street", "postCode", "city", "country" or "endDate". Then we put the first level as index level ("stack(0)") and join the name column to the results.

Note that the data is straight from the API and may have confusing fields (ie. there might not be a city named as "Fortum"). This has nothing to do with this software.

Easy and convenient way to transform the data. We can also use the same method with other columns:

In [18]:
first_level = "businessIdChanges"
(
    df_fortum[
        [col for col in df_fortum.columns if col[0].startswith(first_level)]
    ]
    .stack(0)
    .dropna(axis=1, how="all")
)

                               change  changeDate newBusinessId oldBusinessId  \
businessId
2679784-7  businessIdChanges 0    DIF  2015-06-30     2679784-7     1852303-7
           businessIdChanges 1     47  2015-07-01     2679784-7     1852303-7
2059590-2  businessIdChanges 0    FUU  2007-05-01     1852328-0     2059590-2
           businessIdChanges 1    DIF  2006-12-31     2059590-2     0100468-7
           businessIdChanges 2     47  2007-01-01     2059590-2     0100468-7
2059592-9  businessIdChanges 0    FUU  2007-05-01     0109160-2     2059592-9
           businessIdChanges 1    DIF  2006-12-31     2059592-9     0100468-7
           businessIdChanges 2     47  2007-01-01     2059592-9     0100468-7
1852328-0  businessIdChanges 0    FUU  2013-05-31     1852328-0     1466058-7
           businessIdChanges 1     44  2013-06-01     1852328-0     1466058-7
           businessIdChanges 2    DIF  2004-02-01     1852328-0     1570867-7
           businessIdChanges 3    FUU  2006-01-12     1852328-0     1759819-2
           businessIdChanges 4    FUU  2007-05-01     1852328-0     2059590-2
1852303-7  businessIdChanges 0    DIF  2015-06-30     2679784-7     1852303-7
           businessIdChanges 1     47  2015-07-01     2679784-7     1852303-7
           businessIdChanges 2    DIF  2004-05-01     1852303-7     0111973-2

                                source
businessId
2679784-7  businessIdChanges 0     1.0
           businessIdChanges 1     2.0
2059590-2  businessIdChanges 0     1.0
           businessIdChanges 1     1.0
           businessIdChanges 2     2.0
2059592-9  businessIdChanges 0     1.0
           businessIdChanges 1     1.0
           businessIdChanges 2     2.0
1852328-0  businessIdChanges 0     1.0
           businessIdChanges 1     2.0
           businessIdChanges 2     1.0
           businessIdChanges 3     1.0
           businessIdChanges 4     1.0
1852303-7  businessIdChanges 0     1.0
           businessIdChanges 1     2.0
           businessIdChanges 2     1.0

The codes can also easily be turned in the full name. Please see the API documentation for the codings.

In [19]:
(
    df_fortum[
        [col for col in df_fortum.columns if col[0].startswith("contactDetails")]
    ]
    .stack(0)
    .query('language == "EN" & endDate != endDate')
    .dropna(how="all", axis=1)
)

                             language registrationDate  source       type  \
businessId
2679784-7  contactDetails 2        EN       2015-06-05     0.0  Telephone
2481332-1  contactDetails 2        EN       2012-05-30     0.0  Telephone
2481338-0  contactDetails 2        EN       2012-05-30     0.0  Telephone
2481336-4  contactDetails 2        EN       2012-05-30     0.0  Telephone
2185030-3  contactDetails 2        EN       2008-03-20     0.0  Telephone
2079891-0  contactDetails 11       EN       2007-12-19     0.0        Fax
           contactDetails 8        EN       2007-12-19     0.0  Telephone

                                   value  version
businessId
2679784-7  contactDetails 2     010 4511      1.0
2481332-1  contactDetails 2      0104511      1.0
2481338-0  contactDetails 2      0104511      1.0
2481336-4  contactDetails 2      0104511      1.0
2185030-3  contactDetails 2      0104511      1.0
2079891-0  contactDetails 11  0104532353      1.0
           contactDetails 8      0104511      1.0

Thanks to the versatileness of Pandas, you can also query the data in single line. Note that NaN values are never equal to themselves thus you can query them with using the logic.

## Additional Links

The meaning of "entryCodes" and "typeOfRegistration" can be found from the API's website.
- Entry codes: http://avoindata.prh.fi/tr-codes_v1.fi.txt
- Type of Registration: http://avoindata.prh.fi/tr-type_v1.fi.txt